// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayPilot.Infrastructure.Persistence;

#nullable disable

namespace StayPilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StayPilotDbContext))]
    [Migration("20260630104712_SeedMarketAreas")]
    partial class SeedMarketAreas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StayPilot.Domain.Entities.ListingSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyListingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyListingId", "SnapshotDateUtc");

                    b.ToTable("ListingSnapshots");
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.MarketArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Centro da Cidade"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Olhos de Água"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Montechoro"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Marina de Albufeira - Cerro da Piedade"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Balaia"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Praia da Falésia"
                        },
                        new
                        {
                            Id = 7,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Clube Albufeira"
                        },
                        new
                        {
                            Id = 8,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Praia da Oura - Areias de S. João"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "São Rafael"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Cerro de Águia - Patroves"
                        },
                        new
                        {
                            Id = 11,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Sesmarias"
                        },
                        new
                        {
                            Id = 12,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Albufeira e Olhos de Água",
                            Zone = "Forte São João"
                        },
                        new
                        {
                            Id = 13,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Ferreiras"
                        },
                        new
                        {
                            Id = 14,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Guia",
                            Zone = "Salgados"
                        },
                        new
                        {
                            Id = 15,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Guia",
                            Zone = "Galé"
                        },
                        new
                        {
                            Id = 16,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Guia",
                            Zone = "Vale de Parra"
                        },
                        new
                        {
                            Id = 17,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Albufeira",
                            Town = "Paderne"
                        },
                        new
                        {
                            Id = 18,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Alcoutim",
                            Town = "Alcoutim e Pereiro"
                        },
                        new
                        {
                            Id = 19,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Alcoutim",
                            Town = "Giões"
                        },
                        new
                        {
                            Id = 20,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Alcoutim",
                            Town = "Martim Longo"
                        },
                        new
                        {
                            Id = 21,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Alcoutim",
                            Town = "Vaqueiros"
                        },
                        new
                        {
                            Id = 22,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Aljezur",
                            Town = "Aljezur"
                        },
                        new
                        {
                            Id = 23,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Aljezur",
                            Town = "Bordeira"
                        },
                        new
                        {
                            Id = 24,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Aljezur",
                            Town = "Odeceixe"
                        },
                        new
                        {
                            Id = 25,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Aljezur",
                            Town = "Rogil"
                        },
                        new
                        {
                            Id = 26,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Altura"
                        },
                        new
                        {
                            Id = 27,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Azinhal"
                        },
                        new
                        {
                            Id = 28,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Castro Marim",
                            Zone = "Centro"
                        },
                        new
                        {
                            Id = 29,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Castro Marim",
                            Zone = "Praia Verde"
                        },
                        new
                        {
                            Id = 30,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Castro Marim",
                            Zone = "Quinta do Sobral - São Bartolomeu"
                        },
                        new
                        {
                            Id = 31,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Castro Marim",
                            Zone = "Monte Francisco"
                        },
                        new
                        {
                            Id = 32,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Castro Marim",
                            Zone = "Junqueira - Beliche"
                        },
                        new
                        {
                            Id = 33,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Castro Marim",
                            Zone = "Golf Resort"
                        },
                        new
                        {
                            Id = 34,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Castro Marim",
                            Town = "Odeleite"
                        },
                        new
                        {
                            Id = 35,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Conceição"
                        },
                        new
                        {
                            Id = 36,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Estoi"
                        },
                        new
                        {
                            Id = 37,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "Centro"
                        },
                        new
                        {
                            Id = 38,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "Arneiro - Braciais - Patacão"
                        },
                        new
                        {
                            Id = 39,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "Areal Gordo - Rio Seco - Ilha da Culatra"
                        },
                        new
                        {
                            Id = 40,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "Horta das Figuras - Lejana - Senhora da Saúde"
                        },
                        new
                        {
                            Id = 41,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "Penha - Vale da Amoreira"
                        },
                        new
                        {
                            Id = 42,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "São Luís"
                        },
                        new
                        {
                            Id = 43,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "Alto de Santo António - Bom João - João de Deus"
                        },
                        new
                        {
                            Id = 44,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Faro",
                            Zone = "Alto Rodes"
                        },
                        new
                        {
                            Id = 45,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Montenegro"
                        },
                        new
                        {
                            Id = 46,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Montenegro",
                            Zone = "Quinta do Eucalipto - Ilha de Faro"
                        },
                        new
                        {
                            Id = 47,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Faro",
                            Town = "Santa Bárbara de Nexe"
                        },
                        new
                        {
                            Id = 48,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Estombar e Parchal"
                        },
                        new
                        {
                            Id = 49,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Ferragudo"
                        },
                        new
                        {
                            Id = 50,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Lagoa e Carvoeiro",
                            Zone = "Cidade de Lagoa"
                        },
                        new
                        {
                            Id = 51,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Lagoa e Carvoeiro",
                            Zone = "Centro de Carvoeiro"
                        },
                        new
                        {
                            Id = 52,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Lagoa e Carvoeiro",
                            Zone = "Vale Milho - Vale Centeanes - Algar Seco"
                        },
                        new
                        {
                            Id = 53,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Lagoa e Carvoeiro",
                            Zone = "Salicos - Sesmarias - Boavista"
                        },
                        new
                        {
                            Id = 54,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Lagoa e Carvoeiro",
                            Zone = "Caramujeira - Vale d'El Rei - Benagil"
                        },
                        new
                        {
                            Id = 55,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Lagoa e Carvoeiro",
                            Zone = "Mato Serrão - Vale da Lapa - Vale Currais"
                        },
                        new
                        {
                            Id = 56,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagoa",
                            Town = "Porches"
                        },
                        new
                        {
                            Id = 57,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Barão de São João"
                        },
                        new
                        {
                            Id = 58,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Bensafrim"
                        },
                        new
                        {
                            Id = 59,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Lagos"
                        },
                        new
                        {
                            Id = 60,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Lagos",
                            Zone = "Lagos Cidade"
                        },
                        new
                        {
                            Id = 61,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Lagos",
                            Zone = "Meia Praia"
                        },
                        new
                        {
                            Id = 62,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Lagos",
                            Zone = "Quinta da Boavista"
                        },
                        new
                        {
                            Id = 63,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Lagos",
                            Zone = "Falfeira - Monte Funchal"
                        },
                        new
                        {
                            Id = 64,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Lagos",
                            Zone = "Chinicato - Sargaçal"
                        },
                        new
                        {
                            Id = 65,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Luz"
                        },
                        new
                        {
                            Id = 66,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Lagos",
                            Town = "Odiaxere"
                        },
                        new
                        {
                            Id = 67,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Almancil",
                            Zone = "Centro"
                        },
                        new
                        {
                            Id = 68,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Almancil",
                            Zone = "Vale do Lobo"
                        },
                        new
                        {
                            Id = 69,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Almancil",
                            Zone = "Quinta do Lago - Pinheiros Altos"
                        },
                        new
                        {
                            Id = 70,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Almancil",
                            Zone = "Vale do Garrão - Varandas do Lago - Quinta das Salinas"
                        },
                        new
                        {
                            Id = 71,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Almancil",
                            Zone = "The Village - Fonte Algarve - Quinta Verde"
                        },
                        new
                        {
                            Id = 72,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Almancil",
                            Zone = "Vale Formoso - Vale d'Éguas"
                        },
                        new
                        {
                            Id = 73,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Almancil",
                            Zone = "São Lourenço - São João da Venda"
                        },
                        new
                        {
                            Id = 74,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Alte"
                        },
                        new
                        {
                            Id = 75,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Ameixial"
                        },
                        new
                        {
                            Id = 76,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Benafim"
                        },
                        new
                        {
                            Id = 77,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Boliqueime"
                        },
                        new
                        {
                            Id = 78,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Praia de Quarteira"
                        },
                        new
                        {
                            Id = 79,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Centro - Quarteira Velha"
                        },
                        new
                        {
                            Id = 80,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Fonte Santa"
                        },
                        new
                        {
                            Id = 81,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Aldeia do Golf - Alto do Golf"
                        },
                        new
                        {
                            Id = 82,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Vilamoura"
                        },
                        new
                        {
                            Id = 83,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Marina de Vilamoura"
                        },
                        new
                        {
                            Id = 84,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Pinhal Velho - Terraços do Pinhal - Encosta das Oliveiras"
                        },
                        new
                        {
                            Id = 85,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Quarteira",
                            Zone = "Vila Sol - Morgadinho"
                        },
                        new
                        {
                            Id = 86,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Querença"
                        },
                        new
                        {
                            Id = 87,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Salir"
                        },
                        new
                        {
                            Id = 88,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "São Clemente",
                            Zone = "Centro Histórico Este de Loulé"
                        },
                        new
                        {
                            Id = 89,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "São Clemente",
                            Zone = "Centro Este da Cidade de Loulé"
                        },
                        new
                        {
                            Id = 90,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "São Sebastião",
                            Zone = "Centro Oeste da Cidade de Loulé"
                        },
                        new
                        {
                            Id = 91,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "São Sebastião",
                            Zone = "Cerro de Cabeça de Câmara - Estação de Loulé"
                        },
                        new
                        {
                            Id = 92,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Loulé",
                            Town = "Tor"
                        },
                        new
                        {
                            Id = 93,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Monchique",
                            Town = "Alferce"
                        },
                        new
                        {
                            Id = 94,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Monchique",
                            Town = "Marmelete"
                        },
                        new
                        {
                            Id = 95,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Monchique",
                            Town = "Monchique"
                        },
                        new
                        {
                            Id = 96,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Fuseta"
                        },
                        new
                        {
                            Id = 97,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Moncarapacho"
                        },
                        new
                        {
                            Id = 98,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Olhão",
                            Zone = "Baixa"
                        },
                        new
                        {
                            Id = 99,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Olhão",
                            Zone = "Marina"
                        },
                        new
                        {
                            Id = 100,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Olhão",
                            Zone = "Cavalinha - Bombeiros"
                        },
                        new
                        {
                            Id = 101,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Olhão",
                            Zone = "Estádio"
                        },
                        new
                        {
                            Id = 102,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Pechão"
                        },
                        new
                        {
                            Id = 103,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Olhão",
                            Town = "Quelfes"
                        },
                        new
                        {
                            Id = 104,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Alvor"
                        },
                        new
                        {
                            Id = 105,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Mexilhoeira Grande"
                        },
                        new
                        {
                            Id = 106,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão"
                        },
                        new
                        {
                            Id = 107,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão",
                            Zone = "Portimão Cidade"
                        },
                        new
                        {
                            Id = 108,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão",
                            Zone = "Praia da Rocha"
                        },
                        new
                        {
                            Id = 109,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão",
                            Zone = "Aldeia do Carrasco - Vale da Arrancada"
                        },
                        new
                        {
                            Id = 110,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão",
                            Zone = "Amparo - Alto do Quintão"
                        },
                        new
                        {
                            Id = 111,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão",
                            Zone = "Bemposta - Quatro Estradas"
                        },
                        new
                        {
                            Id = 112,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão",
                            Zone = "Quinta da Malata"
                        },
                        new
                        {
                            Id = 113,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Portimão",
                            Town = "Portimão",
                            Zone = "Vale de Lagar - Quinta das Oliveiras - Pedra Mourinha"
                        },
                        new
                        {
                            Id = 114,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "São Brás de Alportel",
                            Town = "São Brás de Alportel",
                            Zone = "Centro"
                        },
                        new
                        {
                            Id = 115,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "São Brás de Alportel",
                            Town = "São Brás de Alportel",
                            Zone = "Campina - Mesquita"
                        },
                        new
                        {
                            Id = 116,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "São Brás de Alportel",
                            Town = "São Brás de Alportel",
                            Zone = "São Romão - Fonte do Touro"
                        },
                        new
                        {
                            Id = 117,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "São Brás de Alportel",
                            Town = "São Brás de Alportel",
                            Zone = "Funchais - Corotelo"
                        },
                        new
                        {
                            Id = 118,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "São Brás de Alportel",
                            Town = "São Brás de Alportel",
                            Zone = "Barrabés - Peral"
                        },
                        new
                        {
                            Id = 119,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Alcantarilha"
                        },
                        new
                        {
                            Id = 120,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Algoz"
                        },
                        new
                        {
                            Id = 121,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Armação de Pêra"
                        },
                        new
                        {
                            Id = 122,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Pêra"
                        },
                        new
                        {
                            Id = 123,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Silves",
                            Zone = "Centro da Cidade"
                        },
                        new
                        {
                            Id = 124,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Silves",
                            Zone = "Zona Histórica"
                        },
                        new
                        {
                            Id = 125,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Silves",
                            Zone = "Vila Fria"
                        },
                        new
                        {
                            Id = 126,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Silves",
                            Zone = "Vale da Vila - Poço Barreto"
                        },
                        new
                        {
                            Id = 127,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Silves",
                            Zone = "Enxerim - Barrada"
                        },
                        new
                        {
                            Id = 128,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Silves",
                            Zone = "Estação de Silves - Cerro de São Miguel"
                        },
                        new
                        {
                            Id = 129,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Silves",
                            Zone = "Serra - Barragem do Arade"
                        },
                        new
                        {
                            Id = 130,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "São Bartolomeu de Messines"
                        },
                        new
                        {
                            Id = 131,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "São Marcos da Serra"
                        },
                        new
                        {
                            Id = 132,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Silves",
                            Town = "Tunes"
                        },
                        new
                        {
                            Id = 133,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Cabanas de Tavira"
                        },
                        new
                        {
                            Id = 134,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Cachopo"
                        },
                        new
                        {
                            Id = 135,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Conceição"
                        },
                        new
                        {
                            Id = 136,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Luz de Tavira"
                        },
                        new
                        {
                            Id = 137,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Santa Catarina - Fonte do Bispo"
                        },
                        new
                        {
                            Id = 138,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Santa Luzia"
                        },
                        new
                        {
                            Id = 139,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Santo Estêvão"
                        },
                        new
                        {
                            Id = 140,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Tavira"
                        },
                        new
                        {
                            Id = 141,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Tavira",
                            Zone = "Centro Histórico"
                        },
                        new
                        {
                            Id = 142,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Tavira",
                            Zone = "Porta Nova - Colinas da Boavista"
                        },
                        new
                        {
                            Id = 143,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Tavira",
                            Zone = "Pegada - Mato Santo Espírito - Vale Carangueijo"
                        },
                        new
                        {
                            Id = 144,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Tavira",
                            Zone = "Quinta da Foz - Escolas"
                        },
                        new
                        {
                            Id = 145,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Tavira",
                            Zone = "Colina de Asseca - Quinta de Perogil - São Pedro"
                        },
                        new
                        {
                            Id = 146,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Tavira",
                            Town = "Tavira",
                            Zone = "Serra"
                        },
                        new
                        {
                            Id = 147,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Vila do Bispo",
                            Town = "Barão de São Miguel"
                        },
                        new
                        {
                            Id = 148,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Vila do Bispo",
                            Town = "Budens"
                        },
                        new
                        {
                            Id = 149,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Vila do Bispo",
                            Town = "Sagres"
                        },
                        new
                        {
                            Id = 150,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Vila do Bispo",
                            Town = "Vila do Bispo e Raposeira"
                        },
                        new
                        {
                            Id = 151,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Vila Real de Santo António",
                            Town = "Monte Gordo"
                        },
                        new
                        {
                            Id = 152,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Vila Real de Santo António",
                            Town = "Vila Nova de Cacela"
                        },
                        new
                        {
                            Id = 153,
                            Country = "Portugal",
                            CreatedAtUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            District = "Faro",
                            Municipality = "Vila Real de Santo António",
                            Town = "Vila Real de Santo António"
                        });
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.OwnedProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaM2")
                        .HasColumnType("int");

                    b.Property<int>("BalconyCount")
                        .HasColumnType("int");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistanceToBeachMeters")
                        .HasColumnType("int");

                    b.Property<string>("EnergyCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("HasCityView")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasElevator")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGarage")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSeaView")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSwimmingPool")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTerrace")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("MarketAreaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RenovationInvestment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RenovationYear")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("int");

                    b.Property<int>("Typology")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketAreaId");

                    b.ToTable("OwnedProperties");
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.PropertyListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaM2")
                        .HasPrecision(10, 2)
                        .HasColumnType("int");

                    b.Property<int>("BalconyCount")
                        .HasColumnType("int");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistanceToBeachMeters")
                        .HasColumnType("int");

                    b.Property<string>("EnergyCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool?>("HasAirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCityView")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasElevator")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGarage")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSeaView")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSwimmingPool")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTerrace")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFurnished")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("MarketAreaId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int?>("RenovationYear")
                        .HasColumnType("int");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("int");

                    b.Property<int>("Typology")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketAreaId");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("PropertyListings");
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.ListingSnapshot", b =>
                {
                    b.HasOne("StayPilot.Domain.Entities.PropertyListing", "PropertyListing")
                        .WithMany("ListingSnapshots")
                        .HasForeignKey("PropertyListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyListing");
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.OwnedProperty", b =>
                {
                    b.HasOne("StayPilot.Domain.Entities.MarketArea", "MarketArea")
                        .WithMany()
                        .HasForeignKey("MarketAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketArea");
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.PropertyListing", b =>
                {
                    b.HasOne("StayPilot.Domain.Entities.MarketArea", null)
                        .WithMany("Properties")
                        .HasForeignKey("MarketAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.MarketArea", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("StayPilot.Domain.Entities.PropertyListing", b =>
                {
                    b.Navigation("ListingSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
